### ISSUE TITLE
button 컴포넌트 통합 관리에 대한 의문 

### ISSUE THREAD

**Issue by wade3420** [kowoohyuk/todo-list#21]
## Problem

현재 버튼 컴포넌트는 onClick 과 children 만 props 로 받고있습니다. 
그러다보니 각 컴포넌트에서 버튼 컴포넌트를 끌어다 쓸때 styled-component 를 입히는데 약간의 에러 사항이 있습니다. 
공통된 css 가 없다보니 , 한번더 style-component 에서 css 를 주는 방법이나 공통 style을 주는 것이 필요한 것 같습니다.

## Try
우선 버튼 컴포넌트를 스타일컴포넌트로 바꿔서 공통 css 를 줄것을 제안합니다. 

```JSX
import React from 'react';
import styled from 'styled-components'

export default function Button({children, onClick}) {

  const Button = styled.button`
    background-color: transparent;
    border: none;
    cursor: pointer;
  `
  return <Button onClick={onClick}>{children}</Button>;
}
```

이렇게 기본 css 가 들어가 있으면 각 컴포넌트에서 최소한의 css 변경으로 btn을 다룰수있게 될 것입니다.
각자의 컴포넌트에서는 버튼의 css를 상위 style-component 에서 sass 로 컨트롤 하는 것을 제안합니다. 

=> 이 이슈에 대한 코멘트를 다시고 모두가 긍정적일시 업데이트 하겠습니다.

**Comment by kowoohyuk** [comment]
좋습니다!!! 👍 
변경하는 김에 모든 태그의 box-sizing을 border-box로 변경하는 부분과
input 태그처럼 outline, border가 기본적으로 들어간 태그에 대한 처리도 함께 하면 좋을 거 같습니다! 😄

**Comment by wade3420** [comment]
> 좋습니다!!! 👍
> 변경하는 김에 모든 태그의 box-sizing을 border-box로 변경하는 부분과
> input 태그처럼 outline, border가 기본적으로 들어간 태그에 대한 처리도 함께 하면 좋을 거 같습니다! 😄

넵. GlobalStyle  을 app 에 선언하는 방법으로 frame 에 업데이트 하는 방법으로 하면 좋겠네요!

```jsx
import React from 'react';
import { createGlobalStyle } from 'styled-components';

const GlobalStyle = createGlobalStyle`
  body {
    background: #e9ecef;
  }
`;

function App() {
  return (
    <>
      <GlobalStyle />
      <div>안녕하세요</div>
    </>
  );
}

export default App;
```

**Comment by wade3420** [comment]
우선 App.js 에서 GlobalStyle 을 선언하시고 나중에 develop 에 머지하는 방식으로 합니다.

```jsx
import Header from "./Component/Header/Header";
import { createGlobalStyle } from 'styled-components';

const GlobalStyle = createGlobalStyle`
  button {
    background-color: transparent;
    border:none;
    cursor: pointer;
  }

  input:focus {
    outline:none
  }
`;


function App() {
  return (
    <>
      <GlobalStyle/>
      <Header></Header>
      {/* <HistoryList></HistoryList> */}
    </>
  );
}

export default App;

```

**Comment by kowoohyuk** [comment]
> ```js
> createGlobalStyle 
> ```

createGlobalStyle 좋슴다!
그럼 말씀하신대로 분업한 기능 개발 완료하고 나중에 머지하는 걸로!
