### ISSUE TITLE
feature-frame 추가 작업 후 PR

### ISSUE THREAD

**Issue by wade3420** [kowoohyuk/todo-list#8]
[Add] 디렉토리 구조 변경
- Component 폴더 추가
- 재사용성이 높은 Button 컴포넌트화
    - Button.jsx

- 작업 완료 후 develop  에 머지 한다는 룰에 따라 머지했습니다.
- 작자 feature 브랜치에서는 업데이트된 develop 을 pull 해서 사용해 주시길 바랍니다.

**Comment by kowoohyuk** [comment]
확인했습니다!
